2023-03-13 15:05:18,946  INFO - Initializing application...
2023-03-13 15:05:18,958  WARNING -  * Debugger is active!
2023-03-13 15:05:18,965  INFO -  * Debugger PIN: 901-032-737
2023-03-13 15:05:29,873  WARNING - Conversation - Authentication failure
2023-03-13 15:05:29,874  INFO - 127.0.0.1 - - [13/Mar/2023 15:05:29] "[31m[1mPOST /conversation HTTP/1.1[0m" 401 -
2023-03-2023-03-13 15:14:10,464  INFO -  * Restarting with stat
49] "POST /auth/token HTTP/1.1" 200 -
2023-03-13 15:06:04,512  INFO - conversation.get_response
2023-03-13 15:06:05,514  INFO - 127.0.0.1 - - [13/Mar/2023 15:06:05] "POST /conversation HTTP/1.1" 200 -
2023-03-13 15:06:42,074  INFO - conversation.get_response
2023-03-13 15:06:42,312  INFO - error_code=None error_message="'.4' is not of type 'number' - 'temperature'" error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-03-13 15:06:42,312  ERROR - conversation.query_model: '.4' is not of type 'number' - 'temperature'
2023-03-13 15:06:42,548  INFO - 127.0.0.1 - - [13/Mar/2023 15:06:42] "POST /conversation HTTP/1.1" 200 -
2023-03-13 15:07:44,473  WARNING - Conversation - Authentication failure
2023-03-13 15:07:44,475  INFO - 127.0.0.1 - - [13/Mar/2023 15:07:44] "[31m[1mPOST /conversation HTTP/1.1[0m" 401 -
2023-03-13 15:08:53,356  WARNING - Conversation - Authentication failure
2023-03-13 15:08:53,357  INFO - 127.0.0.1 - - [13/Mar/2023 15:08:53] "[31m[1mPOST /conversation HTTP/1.1[0m" 401 -
2023-03-13 15:10:59,899  INFO - 127.0.0.1 - - [13/Mar/2023 15:10:59] "[35m[1mPOST /conversation HTTP/1.1[0m" 500 -
2023-03-13 15:12:19,113  INFO - conversation.get_response
2023-03-13 15:12:20,049  INFO - 127.0.0.1 - - [13/Mar/2023 15:12:20] "POST /conversation HTTP/1.1" 200 -
2023-03-13 15:14:10,034  INFO -  * Detected change in 'c:\\Code\\_dag_poc\\backend\\application.py', reloading
